name: Update README index

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "17 2 * * *"   # dagelijks 02:17 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run generator
        run: |
          python --version
          chmod +x tools/generate_readme.py
          python tools/generate_readme.py

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(readme): auto-update index"
          file_pattern: README.md
